
server:
  port: 8989
spring:
  application:
    name: turbine-stream
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:123456}

eureka:
  client:
    service-url:
       defaultZone: ${EUREKA_SERVER_URL:http://eureka:123456@localhost:8761/eureka/}
