server:
  port: 8989
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:123456}

eureka:
  client:
    service-url:
#      default-zone: http://eureka:123456@discovery-server:8761/eureka/
       default-zone: ${EUREKA_URI:http://eureka::8761/eureka}
