server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://gitee.com/liushaojun/easy-cloud
          search-paths: config-repo
          force-pull: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: user
    password: 123456


  boot:
    admin:
      client:
        url: ${ADMIN_URL:http://localhost:9000}
        username: admin
        password: 123456
#      uri: ${SPRING_COFNIG_URI:http://localhost:9010}
#      override-system-properties: true # 只覆盖 系统属性 和 Env
#      override-none: true # true本地覆盖远程

# Eureka
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://eureka:123456@discovery-server:8761/eureka/}
  instance:
    metadata-map:
      app: ${spring.application.name}
