server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/liushaojun/easy-cloud
          search-paths: config-repo
          force-pull: true


      uri: ${SPRING_COFNIG_URI:http://localhost:9010}
#      override-system-properties: true # 只覆盖 系统属性 和 Env
#      override-none: true # true本地覆盖远程

# Eureka
eureka:
  client:
    service-url:
      default-zone: http://registry-server:8761/eureka/