server:
  port: 9002
spring:
  application:
    name: turbine
eureka:
  client:
    service-url:
      default-zone: http://eureka:123456@discovery-server:8761/eureka/

turbine:
  aggregator:
    clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX3
  appConfig: microservice-consumer-movie-ribbon-with-hystrix3
