version: '3'
services:
  eureka1:
    image: easy-cloud/ec-eureka-ha:1.0-SNAPSHOPT
    hostname: eureka1
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=eureka1
  eureka1:
    image: easy-cloud/ec-eureka-ha:1.0-SNAPSHOPT
    hostname: eureka1
    ports:
      - "8762:8761"
    environment:
     - spring.profiles.active=eureka2
  eureka1:
    image: easy-cloud/ec-eureka-ha:1.0-SNAPSHOPT
    hostname: eureka1
    ports:
      - "8763:8761"
    environment:
      - spring.profiles.active=eureka3