version: '3'
services:
  consumer-service:
    build: ./service/ec-consumer
    expose:
      - "8001"
    links:
      - discovery-server
  edge-service:
    build: ./service/ec-edge-service
    expose:
     - "8070"
    links:
      - discovery-server
  product-service:
    build: ./service/ec-product-service
#    ports:
#      - "8090:8090"
    expose:
      - "8090"
    links:
      - discovery-server
      - zipkin
  user-service:
    build: ./service/ec-user-service
#    ports:
#      - "8081:8081"
    links:
      - discovery-server
      - zipkin
      - mongodb
      - admin-server

  config-server:
    build: ./ec-config
#    ports:
#      - "8888:8888"
    volumes:
          - "/tmp/logs:/app/logs"
    links:
      - discovery-server
      - mongodb
      - admin-server
      - rabbitmq
  api-gateway:
     build: ./ec-api-gateway/ec-zuul
     ports:
      - "8080:8080"
     volumes:
      - "/tmp/logs:/app/logs"
     links:
      - discovery-server
      - zipkin
  dashboard:
     build: ./ec-dashboard
     ports:
       - "9001:9001"
     links:
       - discovery-server
       - admin-server
  turbine-stream:
     build: ./ec-turbine-stream
     ports:
       - "8099:8099"
     links:
       - discovery-server
       - rabbitmq
  admin-server:
    build: ./ec-admin
    ports:
      - "9000:9000"
    environment:
      - "spring.profiles.active=security"
    volumes:
      - "/tmp/logs:/app/logs"
    links:
      - discovery-server
  discovery-server:
    build: ./ec-discovery/ec-eureka-server/
    ports:
      - "8761:8761"
    volumes:
      - "/tmp/logs:/app/logs"
    environment:
      - "EUREKA_URL=http://discovery-server:8761/eureka"

#  mysql:
#    image: msyql:5.7
#    volumes:
#    - ~/data/mysql/data:/var/lib/mysql
#    ports:
#    - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      TZ: Asia/Shanghai
  mongodb:
    image: mongo:3.6.4
    ports:
      - "27017:27017"
    volumes:
      - ~/data/mongo/data:/data/db

  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - 9411:9411
