version: '3'
services:
  eureka1:
    image: easy-cloud/ec-eureka-server-ha:1.0-SNAPSHOT
    hostname: eureka1
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=eureka1
  eureka2:
    image: easy-cloud/ec-eureka-server-ha:1.0-SNAPSHOT
    hostname: eureka2
    ports:
      - "8762:8761"
    environment:
     - spring.profiles.active=eureka2
  eureka3:
    image: easy-cloud/ec-eureka-server-ha:1.0-SNAPSHOT
    hostname: eureka3
    ports:
      - "8763:8761"
    environment:
      - spring.profiles.active=eureka3
