server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${spring.application.name}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

spring:
  application:
    name: registry-server
