server:
  port: 8001
eureka:
  client:
    service-url:
      default-zone: "http://eureka:123456@discovery-server:8761/eureka/"
spring:
  application:
    name: consumer-ribbon
management:
  endpoints:
    web:
      exposure:
        include: "*"
#    自定义LoadBalancer  规则
#user-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000