server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://localhost/db_user
  boot:
      admin:
        client:
          url: http://localhost:9000

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
swagger:
  exclude-path: /error,
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: ${spring.application.name}.log
  level:
    root: error
    com.brook.user: info
