server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}/db_user
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:9000}
        username: admin
        password: 123456
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
  sleuth:
    sampler:
      probability: 1
swagger:
  exclude-path: /error,
management:
  endpoints:
    web:
      exposure:
        include: "*"

