server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}/db_user
  boot:
    admin:
      client:
        instance:
          service-url: http://admin:9000
        url:  ${ADMIN_URI:http://admin:9000}

  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
  sleuth:
    sampler:
      probability: 1
swagger:
  exclude-path: /error,
management:
  endpoints:
    web:
      exposure:
        include: "*"

