server:
  port: 9000
spring:
  application:
    name: admin-server
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

# Discovery
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:123456@localhost:8761/eureka/}
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS