spring:
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://discovery-server:8761/eureka}

