server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: product
        uri: lb://product-service
        predicates:
        - Path=/product/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:123456@localhost:8761/eureka/}
