server:
  port: 8761
spring:
  application:
    name: discovery-server
  security:
    user:
      name: eureka
      password: 123456
eureka:
  instance:
    prefer-ip-address: true
    hostname: discovery
  datacenter: cloud
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: ${EUREKA_URL:http://eureka:123456@${spring.application.name}:${server.port}/eureka/}
  server:
    wait-time-in-ms-when-sync-empty: 0


