server:
  port: 8761
spring:
  application:
    name: discovery-server
  security:
    user:
      password: 123456
      name: eureka
eureka:
  instance:
    prefer-ip-address: true
  datacenter: cloud
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:123456@localhost:${server.port}/eureka/}
  server:
    wait-time-in-ms-when-sync-empty: 0


