
zuul:
  routes: # 默认 以 eureka 注册的服务名进行访问
#    sensitiveHeaders: 如果需要下游Cookies ,headers 配置此敏感头
     user-service: /user/** # Simple
     config-server: /config/**
#     user:
#        path: /user/**
#        service-id: user-service
     product:
        path: /product/**
        service-id: product-service
#  retryable: true #开启重试
management:
  endpoints:
    web:
      exposure:
        include: routes,filters
swagger:
  version: @project.version@
  title: Easy Cloud Api Docs
  contact:
    name: Brook
    email: dev@easy-cloud.com
spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
  sleuth:
    sampler:
      probability: 1