spring:
  application:
    name: discover-server-ha
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
---
spring:
  profiles: eureka1
eureka:
  instance:
    hostname: eureka1
eureka:
  instance:
  client:
    serviceUrl:
      defaultZone: "http://eureka3:${server.port}/eureka/,http://eureka2:${server.port}/eureka/"
---
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: "http://eureka1:${server.port}/eureka/,http://eureka3:${server.port}/eureka/"

---
spring:
  profiles: eureka3
eureka:
  instance:
    hostname: eureka3
  client:
    serviceUrl:
      defaultZone: "http://eureka1:${server.port}/eureka/,http://eureka2:${server.port}/eureka/"