server:
  port: 8070
spring:
  application:
    name: edge-service
  rabbitmq:
    username: user
    password: 123456
eureka:
  client:
    service-url:
      default-zone: http://eureka:123456@discovery-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"