server:
  port: 8070
spring:
  application:
    name: edge-service
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:9000}
        username: admin
        password: 123456
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:123456}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:123456@localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: "*"